services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myesi
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: myesi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  user-service:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://myesi:123456789@postgres:5432/myesi_db
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8001:8001"

volumes:
  pgdata:
  