name: API Gate service CI

on:
    push:
        branches: [develop,main,feature/*]
    pull_request:
        branches: [develop,main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            # ---- Checkout repo ----
            - name: Checkout code
              uses: actions/checkout@v4
            
            # ---- Set up Python ----
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            # ---- Install dependencies ----
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install black ruff pytest

            # ---- Lint (format + static check) ----
            - name: Run linter
              run: |
                black --check app/
                ruff check app/

            # ---- Run tests ----
            - name: Run tests
              run: |
                pytest -v || echo "No tests found yet, skipping..."

            # ---- Build validation ----
            - name: Test build
              run: |
                python -m compileall app
    
    # ---- Optional: Docker build check ----
    # docker-build:
    #     runs-on: ubuntu-latest
    #     needs: build-test
    #     if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4

    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v3

    #         - name: Build Docker image
    #           run: docker build -t myesi/api-gateway:test .